#pragma once

#include <cstdint>

#define END_VIEWPATTERNS     200
#define END_CTRLPATTERNS     400
#define END_VIEWSAMPLES      600
#define END_CTRLSAMPLES      800
#define END_VIEWINSTRUMENTS 1000
#define END_CTRLINSTRUMENTS 1200
#define END_VIEWCOMMENTS    1400
#define END_CTRLCOMMENTS    1800
#define END_VIEWGENERAL     2000
#define END_CTRLGENERAL     2200
#define END_MODDOCUMENT     2400
#define END_MAINFRAME       2600

//not sure why I shoved message IDs here anymore. Might want to move em. -rewbs
enum {
    WM_MOD_UPDATEPOSITION        =        (WM_USER+1973),
    WM_MOD_DESTROYMODDOC,
    WM_MOD_DESTROYPATEDIT,
    WM_MOD_UPDATESOUNDBUFFER,
    WM_MOD_INVALIDATEPATTERNS,
    WM_MOD_DESTROYSAMPLE,
    WM_MOD_DESTROYINSTRUMENT,
    WM_MOD_ACTIVATEVIEW,
    WM_MOD_CHANGEVIEWCLASS,
    WM_MOD_UNLOCKCONTROLS,
    WM_MOD_CTRLMSG,
    WM_MOD_VIEWMSG,
    WM_MOD_TREEMSG,
    WM_MOD_MIDIMSG,
    WM_MOD_GETTOOLTIPTEXT,
    WM_MOD_DRAGONDROPPING,
    WM_MOD_SPECIALKEY,
    WM_MOD_KBDNOTIFY,
    WM_MOD_INSTRSELECTED,
    WM_MOD_KEYCOMMAND,
    WM_MOD_RECORDPARAM,
};
