#!/bin/sh
ROOT=$(cd $(dirname $0)/..; pwd -P)
find $ROOT/src \( -iname '*.cpp' -o -iname '*.h' -o -iname '*.hpp' \) -exec dos2unix {} \;
find $ROOT/src \( -iname '*.cpp' -o -iname '*.h' -o -iname '*.hpp' \) -exec chmod 644 {} \;
